services:
  viewer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm --filter osrs-cache-viewer dev --host 0.0.0.0
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./apps/osrs-cache-viewer
          target: /app/apps/osrs-cache-viewer
          ignore:
            - node_modules/
        - action: sync
          path: ./packages/osrs-cache-loader
          target: /app/packages/osrs-cache-loader
          ignore:
            - node_modules/
        - action: sync
          path: ./internal/ui-preset
          target: /app/internal/ui-preset
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  docs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm --filter osrs-cache-docs dev --host 0.0.0.0
    ports:
      - "4321:4321"
    develop:
      watch:
        - action: sync
          path: ./apps/osrs-cache-docs
          target: /app/apps/osrs-cache-docs
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
